name: la_pri_modas
description: Projeto La Pri Modas
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.21.1
  firebase_analytics: ^9.3.3
  firebase_crashlytics: ^2.8.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/presentation/ui/assets/images/
    - lib/presentation/ui/assets/images/logos/